# Generated by Django 5.0.4 on 2024-07-05 06:49

import posts.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("video_file", models.FileField(upload_to=posts.models.PathAndRename("videos/"))),
                ("thumbnail_file", models.ImageField(upload_to=posts.models.PathAndRename("thumbnails/"))),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
