# Generated by Django 5.0.4 on 2024-07-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="memo",
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
